# Prometheus Configuration for Cardano OTC Trading System
# Comprehensive monitoring setup for production environment

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'otc-production'
    environment: 'production'

# Rules files specifying alerting/recording rules
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'otc-server'

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'otc-postgres'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'otc-redis'

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'otc-nginx'

  # Application metrics (Node.js)
  - job_name: 'otc-app'
    static_configs:
      - targets: ['app:4000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'otc-application'
    # Custom labels for application metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'nodejs_.*'
        target_label: service
        replacement: 'otc-backend'

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'otc-docker'

  # Custom application metrics
  - job_name: 'otc-custom-metrics'
    static_configs:
      - targets: ['app:4000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    basic_auth:
      username: 'metrics'
      password: 'secure_metrics_password'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'otc-app-custom'

  # Blockchain monitoring (optional)
  - job_name: 'cardano-node'
    static_configs:
      - targets: ['cardano-node:12798']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'cardano-mainnet'

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "remote_user"
#       password: "remote_password"

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint.com/api/v1/read"
#     basic_auth:
#       username: "remote_user"
#       password: "remote_password"